Revert "Update isAvailable methods in connman and network manager clients."
This reverts commit 983018f911e0553a87c53c4e020290d28cb4c237.

Reverting because the change broke compilation with GDBus libdbus, where
getConnection sometimes still returns a plain pointer:

/home/pohly/syncevolution/syncevolution/src/dbus/server/connman-client.h:48:48: error: member reference type
      'DBusConnection *' is a pointer; maybe you meant to use '->'?
    bool isAvailable() { return getConnection().get() != NULL; }