GTK-3 UI: fixed compile problem
The GTK-3 UI depends on a class from gio-unix-2.0 and failed
to compile on Fedora Core 16 because the configure checks for
that lib (and thus the compiler flags) were missing:

src/gtk3-ui/sync-ui.c:30:33: fatal error: gio/gdesktopappinfo.h: No such file or directory

Reported by Peter Robinson.